#!/bin/bash

# Manual Startup Commands for DevOps CI/CD Dashboard
# Run each step in a separate terminal window

echo "=== DevOps CI/CD Dashboard - Manual Setup ==="
echo ""

echo "STEP 1: Start MongoDB (Terminal 1)"
echo "======================================"
echo "export PATH=\"/usr/local/mongodb/bin:\$PATH\""
echo "mongod --dbpath /usr/local/var/mongodb --logpath /usr/local/var/log/mongodb/mongo.log --fork"
echo ""
echo "Verify MongoDB is running:"
echo "ps aux | grep mongod"
echo ""

echo "STEP 2: Start Backend Server (Terminal 2)"
echo "=========================================="
echo "cd backend"
echo "node server-mongodb.js"
echo ""
echo "Verify backend is working:"
echo "curl http://localhost:5002/health"
echo "curl http://localhost:5002/api/pipelines"
echo ""

echo "STEP 3: Start Frontend Server (Terminal 3)"
echo "============================================"
echo "cd ..  # Back to project root"
echo "python3 -m http.server 8000"
echo ""
echo "Verify frontend is working:"
echo "curl http://localhost:8000"
echo ""

echo "STEP 4: Access Dashboard"
echo "========================"
echo "Open browser and go to: http://localhost:8000"
echo "Backend API: http://localhost:5002"
echo "Health Check: http://localhost:5002/health"
echo ""

echo "=== TROUBLESHOOTING ==="
echo ""
echo "If MongoDB doesn't start:"
echo "  - Check if MongoDB is installed: which mongod"
echo "  - Install MongoDB if missing (see README.md)"
echo ""
echo "If backend doesn't start:"
echo "  - Check if MongoDB is running first"
echo "  - Verify port 5002 is not in use: lsof -i :5002"
echo "  - Check backend logs for errors"
echo ""
echo "If frontend doesn't start:"
echo "  - Check if port 8000 is not in use: lsof -i :8000"
echo "  - Try different port: python3 -m http.server 8001"
echo ""
echo "=== STOPPING SERVICES ==="
echo ""
echo "Stop MongoDB: mongod --shutdown"
echo "Stop Backend: Ctrl+C in Terminal 2"
echo "Stop Frontend: Ctrl+C in Terminal 3"
